# Generated by Django 4.0.1 on 2022-01-27 07:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authen', '0003_alter_registermodel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdetails',
            fields=[
                ('caid', models.BigAutoField(primary_key=True, serialize=False)),
                ('cafirst', models.CharField(max_length=50)),
                ('caphone', models.BigIntegerField()),
                ('caemail', models.EmailField(max_length=50)),
                ('caaddress1', models.TextField()),
                ('caaddress2', models.TextField()),
                ('cacountry', models.CharField(max_length=25)),
                ('castate', models.CharField(max_length=25)),
                ('capin', models.IntegerField()),
                ('cashippingbill', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('cartdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='carts.cartdetails')),
                ('pid', models.BigAutoField(primary_key=True, serialize=False)),
                ('pdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ptotal', models.FloatField()),
                ('pcustid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.registermodel')),
            ],
            bases=('carts.cartdetails',),
        ),
        migrations.CreateModel(
            name='cartmodel',
            fields=[
                ('coid', models.AutoField(primary_key=True, serialize=False)),
                ('coprodid', models.IntegerField()),
                ('copname', models.CharField(max_length=50)),
                ('comodelid', models.CharField(max_length=30)),
                ('coprice', models.FloatField()),
                ('codiscount', models.FloatField()),
                ('cocustid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.registermodel')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('purchase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='carts.purchase')),
                ('paytype', models.CharField(max_length=50)),
                ('paycname', models.CharField(max_length=50)),
                ('paycno', models.BigIntegerField()),
                ('payexpr', models.CharField(max_length=10)),
                ('paycvv', models.CharField(max_length=5)),
            ],
            bases=('carts.purchase',),
        ),
        migrations.CreateModel(
            name='parchasedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coprodid', models.IntegerField()),
                ('copname', models.CharField(max_length=50)),
                ('comodelid', models.CharField(max_length=30)),
                ('coprice', models.FloatField()),
                ('codiscount', models.FloatField()),
                ('pdid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.purchase')),
            ],
        ),
    ]
