# Generated by Django 4.0.1 on 2022-01-28 06:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_alter_registermodel_phone'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parchasedetails',
            name='pdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='parchasedetails',
            name='pucustid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authen.registermodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartdetails',
            name='cashippingbill',
            field=models.BooleanField(default=False),
        ),
    ]
