# Generated by Django 4.0.1 on 2022-01-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registermodel',
            name='gender',
            field=models.CharField(choices=[['Male', 'MALE'], ['Female', 'FEMALE']], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
