# Generated by Django 4.0.1 on 2022-01-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_registermodel_age_registermodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='phone',
            field=models.BigIntegerField(unique=True),
        ),
    ]
